name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: nuxt/actions-yarn@master
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn run lint
